ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS family_details JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS bank_details JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS personal_details JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS address JSONB DEFAULT '{}';
