CREATE TABLE IF NOT EXISTS employee (
    id SERIAL PRIMARY KEY,
    start_time TIMESTAMP,
    completion_time TIMESTAMP,
    email VARCHAR(255),
    name VARCHAR(255),
    full_name VARCHAR(255),
    dob VARCHAR(50),
    joining_date VARCHAR(50),
    designation VARCHAR(255),
    department VARCHAR(255),
    marital_status VARCHAR(50),
    pan VARCHAR(50),
    adhar_no VARCHAR(50),
    mobile_no VARCHAR(50),
    emergency_contact_no TEXT,
    personal_mail_id VARCHAR(255),
    blood_group VARCHAR(20),
    bank_name VARCHAR(255),
    account_number VARCHAR(100),
    ifsc VARCHAR(50),
    bank_branch VARCHAR(255),
    uan_no VARCHAR(100),
    current_address TEXT,
    permanent_address TEXT,
    language_known TEXT,
    
    -- Family Details
    name_1 VARCHAR(255),
    relation VARCHAR(100),
    occupation VARCHAR(255),
    age VARCHAR(50),
    contact VARCHAR(50),
    
    name_2 VARCHAR(255),
    relation1 VARCHAR(100),
    occupation1 VARCHAR(255),
    age1 VARCHAR(50),
    contact1 VARCHAR(50),
    
    name_3 VARCHAR(255),
    relation2 VARCHAR(100),
    occupation2 VARCHAR(255),
    age2 VARCHAR(50),
    
    name_4 VARCHAR(255),
    relation3 VARCHAR(100),
    occupation3 VARCHAR(255),
    age3 VARCHAR(50),
    
    -- Qualifications
    qualification_1 VARCHAR(255),
    college_name VARCHAR(255),
    passout_year VARCHAR(50),
    grade_percentage VARCHAR(50),
    
    qualification_2 VARCHAR(255),
    college_name1 VARCHAR(255),
    passout_year1 VARCHAR(50),
    grade_percentage1 VARCHAR(50),
    
    qualification_3 VARCHAR(255),
    college_name2 VARCHAR(255),
    passout_year2 VARCHAR(50),
    grade_percentage2 VARCHAR(50),
    
    -- Previous Employment
    previous_employer_name VARCHAR(255),
    designation1 VARCHAR(255),
    period_of_work VARCHAR(100),
    reason_of_leaving TEXT,
    reporting_manager_contact_email TEXT,
    
    -- Documents
    current_address_proof TEXT,
    permanent_address_proof TEXT,
    pan1 TEXT,
    bank_details_proof TEXT,
    ssc_10th_certificate TEXT,
    hsc_12th_certificate TEXT,
    graduation_certificate TEXT,
    post_graduation TEXT,
    previous_employment_experience_letter TEXT,
    previous_employment_offer_letter TEXT,
    previous_employment_salary_slip TEXT,
    updated_resume TEXT,
    passport_size_photo TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
